%%{init: {'theme': 'base', 'themeVariables': { 'actorBkg': '#6366f1', 'actorTextColor': '#ffffff', 'actorBorder': '#4338ca', 'noteBkg': '#f8fafc', 'noteBorder': '#cbd5e1', 'signalColor': '#475569', 'loopTextColor': '#1e293b' }}}%%
sequenceDiagram
    participant R as Registry (ghcr.io/opensource-distroless)
    participant GH as GitHub Action (CC Assembler)
    participant Sec as Security (Cosign)
    
    GH->>R: Pull `base:latest` and `artifacts-gcc:latest`
    R-->>GH: Download trusted ancestral OS and C++ blobs
    
    GH->>Sec: `cosign verify` parent lineages
    Sec-->>GH: Pass (Identities Match OIDC)
    
    GH->>GH: `FROM base:latest` \n `COPY --from=artifacts-gcc / /`
    
    GH->>R: Push updated runtime (cc:latest)
    GH->>Sec: `cosign sign` Final OCI Manifest
