%%{init: {'theme': 'base', 'themeVariables': { 'actorBkg': '#6366f1', 'actorTextColor': '#ffffff', 'actorBorder': '#4338ca', 'noteBkg': '#f8fafc', 'noteBorder': '#cbd5e1', 'signalColor': '#475569', 'loopTextColor': '#1e293b' }}}%%
sequenceDiagram
    participant GH as GitHub Action
    participant S as Source (zlib.net)
    participant Sec as Security (Trivy)
    participant R as Registry (ghcr.io/opensource-distroless)
    
    GH->>S: curl zlib-1.x.tar.gz
    S-->>GH: Download pristine source
    
    GH->>GH: Native Compile (Fedora sandbox)
    
    GH->>Sec: Trivy SCA/SBOM scan on compiled tar.gz
    Sec-->>GH: output: zlib-sbom.spdx.json
    
    GH->>R: Push intermediate scratch container (artifacts-zlib)
    GH->>R: Sign via Cosign OIDC credentials
