sequenceDiagram
    participant GH as GitHub Action
    participant S as Source (openssl.org)
    participant Sec as Security (Semgrep/Trivy)
    participant R as Registry (ghcr.io/opensource-distroless)
    
    GH->>S: curl openssl-3.x.tar.gz
    S-->>GH: Download pristine source
    GH->>Sec: Semgrep static SAST scan
    Sec-->>GH: Pass
    
    GH->>GH: Execute `./config no-shared -O3` in alpine sandbox
    
    GH->>Sec: Trivy SCA/SBOM scan on compiled tar.gz
    Sec-->>GH: output: openssl-sbom.spdx.json
    
    GH->>R: Push intermediate scratch container (artifacts-openssl)
    GH->>R: Sign via Cosign OIDC credentials
