name: Opensource Distroless Assembler - go-cgo

on:
  workflow_dispatch:
  workflow_call:

jobs:
  assemble:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          
      - name: Build Sovereign Go Binary (Cgo Enabled)
        run: |
          mkdir -p payload
          # We need a gcc to build cgo
          sudo apt-get update && sudo apt-get install -y gcc-multilib
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o payload/app-go-cgo app/test-cgo.go
          
      - name: Authenticate to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Construct Go-Cgo Execution Environment
        id: push
        run: |
          cat <<EOF > Dockerfile
          FROM ghcr.io/${{ github.repository_owner }}/base:latest
          COPY payload/app-go-cgo /usr/bin/app-go-cgo
          USER 0:0
          ENTRYPOINT ["/usr/bin/app-go-cgo"]
          EOF
          
          docker build -t ghcr.io/${{ github.repository_owner }}/go-cgo:latest .
          docker push ghcr.io/${{ github.repository_owner }}/go-cgo:latest
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "ghcr.io/${{ github.repository_owner }}/go-cgo:latest" | cut -d'@' -f2)
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Generate SLSA Build Provenance (Level 3)
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository_owner }}/go-cgo
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
