name: "Stack: Runtime Assembly"

on:
  workflow_dispatch:
    inputs:
      stack:
        description: 'Language stack to build (e.g. python)'
        required: true
        default: 'python'
      push:
        description: 'Push images to registry'
        type: boolean
        required: true
        default: true

jobs:
  assemble:
    uses: ./.github/workflows/distroless-bake-master.yml
    with:
      stack: ${{ github.event.inputs.stack }}
      push: ${{ github.event.inputs.push }}
    secrets: inherit
