name: Distroless The Hard Way - E2E Orchestrator

on:
  workflow_dispatch:

jobs:
  stage_0_bootstrap:
    uses: ./.github/workflows/build-bootstrap.yml

  stage_1_glibc:
    needs: stage_0_bootstrap
    uses: ./.github/workflows/build-glibc.yml

  stage_1_openssl:
    needs: stage_0_bootstrap
    uses: ./.github/workflows/build-openssl.yml

  stage_1_zlib:
    needs: stage_0_bootstrap
    uses: ./.github/workflows/build-zlib.yml

  stage_1_tzdata:
    needs: stage_0_bootstrap
    uses: ./.github/workflows/build-tzdata.yml

  stage_2_base:
    needs: [stage_1_glibc, stage_1_openssl, stage_1_zlib, stage_1_tzdata]
    uses: ./.github/workflows/assemble-base.yml

  stage_3_gcc:
    needs: stage_2_base
    uses: ./.github/workflows/build-gcc.yml

  stage_3_cc:
    needs: stage_3_gcc
    uses: ./.github/workflows/assemble-cc.yml

  e2e_test_java:
    needs: stage_3_cc
    uses: ./.github/workflows/test-java.yml

  e2e_test_nodejs:
    needs: stage_3_cc
    uses: ./.github/workflows/test-nodejs.yml

  e2e_test_python3:
    needs: stage_3_cc
    uses: ./.github/workflows/test-python3.yml

  e2e_test_dotnet:
    needs: stage_3_cc
    uses: ./.github/workflows/test-dotnet.yml

  e2e_test_php:
    needs: stage_3_cc
    uses: ./.github/workflows/test-php.yml

  e2e_test_perl:
    needs: stage_3_cc
    uses: ./.github/workflows/test-perl.yml
