name: Opensource Distroless Mirror - Base Alpine

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Weekly refresh

jobs:
  cache-alpine:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Mirror Alpine Image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/base-alpine:latest"
          # Attempt to pull from Docker Hub (canonical)
          docker pull alpine:latest
          docker tag alpine:latest $IMAGE_NAME
          docker push $IMAGE_NAME
          echo "Mirror successful: $IMAGE_NAME"
